name: Count Lines of Code

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write # Allow the workflow to push to the repository

jobs:
  count-loc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Count lines in all files excluding .git directory
      - name: Count lines in all files
        id: count_lines
        run: |
          echo "Counting lines in all files excluding .git directory:"
          output=$(find . -type f -not -path './.git/*' -exec wc -l {} \; | sort -nr)
          echo "$output" > output.txt  # Save output to a file

          # Calculate grand total
          total=$(awk '{s+=$1} END {print s}' output.txt)

          # Save formatted output and append the grand total
          echo "$output" > formatted_output.txt
          echo "Grand Total: $total" >> formatted_output.txt

          # Set the output as an environment variable
          echo "GRAND_TOTAL=$total" >> $GITHUB_ENV

      # Display the result in a formatted manner
      - name: Display result
        run: |
          echo "Line count completed. Here are the results:"
          cat output.txt | awk '{print "File: " $2, "Lines: " $1}'
          echo "Grand Total: $GRAND_TOTAL"

      # Append results to README
      - name: Append results to README
        run: |
          echo "" >> README.md  # Add a blank line for separation
          echo "Commit: ${{ github.sha }}" >> README.md
          echo "" >> README.md  # Add a blank line after commit info

          # Format the output with tabs for indentation
          while read -r line; do
          echo -e "$line" >> README.md
          done < formatted_output.txt

          echo "" >> README.md  # Add a blank line for separation
          echo "Grand Total: $GRAND_TOTAL" >> README.md
          echo "" >> README.md  # Add a blank line for separation
          echo "#####" >> README.md  # Add the delimiter at the end

          # Commit the updated README
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with CI/CD line count results"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
