name: Count Lines of Code

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  count-loc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cloc
        run: sudo apt-get install -y cloc

      # Count lines of code, including .txt files
      - name: Count lines of code (including .txt)
        run: cloc --force-lang=Plain_Text --include-ext=txt --by-file .

      # Optionally print the result
      - name: Display result
        run: cloc --force-lang=Plain_Text --include-ext=txt --by-file . --quiet

      - name: Save LOC count artifact
        run: cloc --force-lang=Plain_Text --include-ext=txt --by-file . --quiet --out=loc.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: loc-count
          path: loc.txt
