name: Count Lines of Code

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  count-loc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Count lines in all files excluding .git directory
      - name: Count lines in all files
        id: count_lines
        run: |
          echo "Counting lines in all files excluding .git directory:"
          output=$(find . -type f -not -path './.git/*' -exec wc -l {} \;)
          echo "$output"
          echo "::set-output name=lines::$output"  # Save output for later use

      # Display the result in a formatted manner
      - name: Display result
        run: |
          echo "Line count completed. Here are the results:"
          echo "${{ steps.count_lines.outputs.lines }}"
