name: Count Lines of Code

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  count-loc:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install cloc (Count Lines of Code) tool
      - name: Install cloc
        run: sudo apt-get install -y cloc

      # Count the lines of code in the repository
      - name: Count lines of code
        run: cloc .

      # Optionally print the result
      - name: Display result
        run: cloc . --quiet

      # Save the result as an artifact (optional)
      - name: Save LOC count artifact
        run: cloc . --quiet --out=loc.txt

      # Upload the artifact to GitHub for download
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: loc-count
          path: loc.txt
