name: Count Lines of Code

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  count-loc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Count lines of code in .txt files using wc
      - name: Count lines in .txt files
        run: |
          echo "Counting lines in .txt files:"
          find . -name "*.txt" -exec wc -l {} \;

      # Optionally print the result
      - name: Display result
        run: |
          echo "Line count completed."
