name: Count Lines of Code

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  count-loc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Count lines in all files excluding .git directory
      - name: Count lines in all files
        id: count_lines
        run: |
          echo "Counting lines in all files excluding .git directory:"
          output=$(find . -type f -not -path './.git/*' -exec wc -l {} \; | sort -nr)
          echo "$output" > output.txt  # Save output to a file

          # Calculate grand total
          total=$(awk '{s+=$1} END {print s}' output.txt)
          echo "$output" > formatted_output.txt
          echo "Grand Total: $total" >> formatted_output.txt

          echo "lines<<EOF" >> $GITHUB_ENV
          cat formatted_output.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # Display the result in a formatted manner
      - name: Display result
        run: |
          echo "Line count completed. Here are the results:"
          echo "$lines" | awk '{if (NF > 1) {print "File: " $2, "Lines: " $1} else {print $0}}'
